[tool.poetry]
name = "az"
version = "0.1.0"
description = ""
authors = ["Ruslan Gorbunov <fuldax17@gmail.com>"]

[tool.poetry.dependencies]
python = "3.9"
Django = "^3.2.6"
djangorestframework = "^3.12.4"
Pillow = "^8.3.1"
psycopg2 = "^2.9.1"
djoser = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
